### ISSUE TITLE
Improve readme db setup

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#378]
Probably the readme is missing a step about something about installing / turning on postgres, figure out what it is and add it

```
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.
You should use PG::Connection, PG::Result, and PG::Error instead, respectively.
Called from /home/user/.rvm/gems/ruby-2.5.5/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
could not connect to server: Connection refused
    Is the server running on host "localhost" (127.0.0.1) and accepting
    TCP/IP connections on port 5432?
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/home/user/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/home/user/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_handling.rb:87:in `connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/postgresql_database_tasks.rb:6:in `connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/postgresql_database_tasks.rb:15:in `create'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:93:in `create'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:107:in `block in create_current'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:278:in `block in each_current_configuration'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:277:in `each'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:277:in `each_current_configuration'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:106:in `create_current'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/home/user/.rvm/gems/ruby-2.5.5/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.5.5/bin/rake:23:in `load'
/home/user/.rvm/gems/ruby-2.5.5/bin/rake:23:in `<main>'
/home/user/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
/home/user/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
Couldn't create database for {"adapter"=>"postgresql", "host"=>"localhost", "encoding"=>"unicode", "database"=>"doubleunion_development", "pool"=>5, "username"=>"postgres", "password"=>nil, "template"=>"template0"}
could not connect to server: Connection refused
    Is the server running on host "localhost" (127.0.0.1) and accepting
    TCP/IP connections on port 5432?
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/home/user/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/home/user/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/connection_handling.rb:87:in `connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/postgresql_database_tasks.rb:6:in `connection'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/postgresql_database_tasks.rb:15:in `create'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:93:in `create'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:107:in `block in create_current'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:278:in `block in each_current_configuration'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:277:in `each'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:277:in `each_current_configuration'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:106:in `create_current'
/home/user/.rvm/gems/ruby-2.5.5/gems/activerecord-4.2.11.1/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/home/user/.rvm/gems/ruby-2.5.5/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/home/user/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.5.5/bin/rake:23:in `load'
/home/user/.rvm/gems/ruby-2.5.5/bin/rake:23:in `<main>'
/home/user/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
/home/user/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
Couldn't create database for {"adapter"=>"postgresql", "host"=>"localhost", "encoding"=>"unicode", "database"=>"doubleunion_test", "pool"=>5, "username"=>"postgres", "password"=>nil, "template"=>"template0"}
```

Maybe this (database.example.yml)
```
  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5432
```

**Comment by sylphiae** [comment]
This was fixed by commenting out #host localhost in database.yml and the line underneath "Database administrative login by Unix domain socket" in pg_hba.conf. Also in pg_hba.conf the METHOD "trust" was added to the line after "local" is for Unix domain socket connections only.

**Comment by compwron** [comment]
Great! I will close this then since it is working now. It's in the historical issues list so it will be findable... we might also want to put it in the readme but I'm not sure how
