### ISSUE TITLE
Installation issue during Docker setup

### ISSUE THREAD

**Issue by vphong** [doubleunion/arooo#412]
Hey, so I'm trying to get aroo up and running on my machine. Following the steps on the readme, everything's fine up until step 5 of Docker setup: `docker-compose run --rm app bundle exec rake db:setup`. Can someone help me out with this error? Specifically, it looks like the loop at `/app/db/seeds.rb:11` causes `TypeError: no implicit conversion of nil into String`. I'm not familiar enough with the codebase to know what this does.

```sh
$ docker-compose run --rm app bundle exec rake db:setup --trace

Starting arooo_db_1 ... done

WARNING: Skipping key "SECRET_TOKEN". Already set in ENV.
** Invoke db:setup (first_time)
** Invoke db:schema:load_if_ruby (first_time)
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /bundle/vendor/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
doubleunion_development already exists
** Invoke environment (first_time)
** Execute environment
** Execute db:schema:load_if_ruby
** Invoke db:schema:load (first_time)
** Invoke environment 
** Invoke db:load_config 
** Execute db:schema:load
-- enable_extension("plpgsql")
   -> 0.0407s
-- create_table("applications", {:force=>:cascade})
   -> 0.0252s
-- add_index("applications", ["state"], {:name=>"index_applications_on_state", :using=>:btree})
   -> 0.0116s
-- add_index("applications", ["user_id"], {:name=>"index_applications_on_user_id", :using=>:btree})
   -> 0.0102s
-- create_table("authentications", {:force=>:cascade})
   -> 0.0143s
-- create_table("comments", {:force=>:cascade})
   -> 0.0213s
-- add_index("comments", ["user_id"], {:name=>"index_comments_on_user_id", :using=>:btree})
   -> 0.0294s
-- create_table("configurables", {:force=>:cascade})
   -> 0.0282s
-- add_index("configurables", ["name"], {:name=>"index_configurables_on_name", :using=>:btree})
   -> 0.0104s
-- create_table("profiles", {:force=>:cascade})
   -> 0.0163s
-- add_index("profiles", ["user_id"], {:name=>"index_profiles_on_user_id", :using=>:btree})
   -> 0.0091s
-- create_table("sponsorships", {:force=>:cascade})
   -> 0.0107s
-- create_table("users", {:force=>:cascade})
   -> 0.0180s
-- create_table("votes", {:force=>:cascade})
   -> 0.0179s
-- add_index("votes", ["application_id"], {:name=>"index_votes_on_application_id", :using=>:btree})
   -> 0.0091s
-- add_index("votes", ["user_id", "application_id"], {:name=>"index_votes_on_user_id_and_application_id", :using=>:btree})
   -> 0.0075s
-- add_index("votes", ["user_id"], {:name=>"index_votes_on_user_id", :using=>:btree})
   -> 0.0066s
-- initialize_schema_migrations_table()
   -> 0.0023s
** Invoke db:structure:load_if_sql (first_time)
** Invoke db:create 
** Invoke environment 
** Execute db:structure:load_if_sql
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment 
** Execute db:abort_if_pending_migrations
ROLES
rake aborted!
TypeError: no implicit conversion of nil into String
/usr/local/lib/ruby/2.5.0/psych.rb:402:in `parse'
/usr/local/lib/ruby/2.5.0/psych.rb:402:in `parse_stream'
/usr/local/lib/ruby/2.5.0/psych.rb:350:in `parse'
/usr/local/lib/ruby/2.5.0/psych.rb:263:in `load'
/app/db/seeds.rb:11:in `<top (required)>'
/bundle/vendor/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
/bundle/vendor/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
/bundle/vendor/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/bundle/vendor/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
/bundle/vendor/gems/railties-4.2.11.1/lib/rails/engine.rb:547:in `load_seed'
/bundle/vendor/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:253:in `load_seed'
/bundle/vendor/gems/activerecord-4.2.11.1/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/bundle/vendor/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/bundle/vendor/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/bundle/vendor/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/bundle/vendor/gems/bugsnag-6.12.1/lib/bugsnag/integrations/rake.rb:19:in `execute'
/bundle/vendor/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
/bundle/vendor/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/bundle/vendor/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/bundle/vendor/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/bundle/vendor/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/bundle/vendor/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
/bundle/vendor/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/bundle/vendor/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/bundle/vendor/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/bundle/vendor/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/bundle/vendor/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/bundle/vendor/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/bundle/vendor/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/bundle/vendor/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/bundle/vendor/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/bundle/vendor/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/bundle/vendor/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/bundle/vendor/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/bundle/vendor/bin/rake:23:in `load'
/bundle/vendor/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => db:setup => db:seed```

**Comment by compwron** [comment]
Thanks for reporting this issue! I'm not sure yet how to fix it but someone will look into it soon. :)

**Comment by anaulin** [comment]
This has been dormant for a long time, so I'm assuming it is no longer relevant and I'll close it. @vphong if you'd still like assistance with this, please re-open and I'll help you figure it out.
