### ISSUE TITLE
When called without a door code, the doorbell/sms endpoint throws a 500

### ISSUE THREAD

**Issue by anaulin** [doubleunion/arooo#475]
It would be good to return a more graceful error instead.

Example stack trace:
```
app/controllers/doorbell_controller.rb:27:in `block in sms': undefined method `strip' for nil:NilClass (NoMethodError)
    from vendor/bundle/ruby/2.7.0/gems/twilio-ruby-5.39.2/lib/twilio-ruby/twiml/messaging_response.rb:18:in `initialize'
    from app/controllers/doorbell_controller.rb:26:in `new'
    from app/controllers/doorbell_controller.rb:26:in `sms'
    from vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
    from vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.3/lib/abstract_controller/base.rb:194:in `process_action'
    from vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
    from vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    from vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:132:in `run_callbacks'
    from vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
    from vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
    from vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
    from vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `block in instrument'
    from vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
    from vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `instrument'
    from vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
    from vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
    from vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
```

Bugsnag example error:
https://app.bugsnag.com/double-union/du-arooo/errors/5f2c2aeb7c0ed20018107e7b?filters[error.status][0][type]=eq&filters[error.status][0][value]=for_review

Curl command to reproduce:
```
curl --request GET \
  --header 'Accept-Encoding: gzip' \
  --header 'Cf-Ipcountry: US' \
  --header 'Cf-Ray: 5bea03dc594d0564-LAX' \
  --header 'Cf-Visitor: {"scheme":"https"}' \
  --header 'Upgrade-Insecure-Requests: 1' \
  --header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36' \
  --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  --header 'Sec-Fetch-Site: none' \
  --header 'Sec-Fetch-Mode: navigate' \
  --header 'Sec-Fetch-User: ?1' \
  --header 'Sec-Fetch-Dest: document' \
  --header 'Accept-Language: en-US,en;q=0.9,es;q=0.8,ru;q=0.7,de;q=0.6' \
  --header 'Cookie: [FILTERED]' \
  --header 'Cf-Request-Id: 046620bdbb00000564be87e200000001' \
  --header 'Cf-Connecting-Ip: 2600:2108:10:9ac0:9837:fc3:8bae:499f' \
  --header 'Cdn-Loop: cloudflare' \
  --header 'Connect-Time: 1' \
  --header 'X-Request-Start: 1596730091005' \
  --header 'Total-Route-Time: 0' \
  'https://app.doubleunion.org/doorbell/sms'
```

**Comment by LittleBigProgramming** [comment]
I would like to work on this if it's still available 😃

**Comment by anaulin** [comment]
It is, @LittleBigProgramming ! Assigned to you.

**Comment by LittleBigProgramming** [comment]
Hi, 

I've been taking a look into this and based off the tests the `params['Body]` inside the sms endpoint of `/arooo/app/controllers/doorbell_controller.rb` was either "" or nil. 

So I added the following code with a test alongside but it never seems to pass correctly 🤔 
![image](https://user-images.githubusercontent.com/20643587/97117182-efc0f480-16f9-11eb-8a55-23e04838b6b0.png)

I don't know if I am just looking in the wrong place or not? Here is the spec test I added just proves useful
```
    context "without a doorcode" do
      let(:door_code) { nil }
      subject { get :sms, params: { Body: nil } }

      it "should raise a NoMethodError with better error message" do
        subject
        expect(subject).to raise_error.with_message(/a doorcode was not provided/)
     end
   end
```

Any ideas where I could be going wrong? 🙈🙂

**Comment by anaulin** [comment]
@LittleBigProgramming I think the issue is that if you're expecting an exception to be raised, you need to be passing the subject into `expect` as a block (i.e. between curly braces), and not as a plain parameter. This test case works as intended for me:
```
# in doorbell_controller_spec.rb, line 101
    context "without a doorcode" do
      subject { get :sms }

      it "should raise a NoMethodError with better error message" do
        expect { subject }.to raise_error.with_message(/a doorcode was not provided/)
     end
   end
```

Also note that in my test case I removed the params altogether, since that is the more realistic test case, I think (i.e. someone just calling the URL without any body).

A final note is that I think we should add the guard clause on line 26 in `doorbell_controller.rb`, outside the block. It is a little bit more clear that way: the method does nothing unless `params['Body']` is present.

**Comment by LittleBigProgramming** [comment]
Thank you very much for you feedback I have made the relevant changes amd raised a PR 🙂

I am rarely new to RSpec so thank you very much for the clarification on passing the block into the expect! 🙏🙈
