### ISSUE TITLE
Upgrade ruby

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#773]
Check `.ruby-version` for what ruby we are using. Look at https://www.ruby-lang.org/en/downloads/releases/ and upgrade *one* version per PR until we are at the latest mainstream supported version (currently 3.2.1).

**Comment by fchatterji** [comment]
Hey @compwron, can i work on this issue?

**Comment by compwron** [comment]
@fchatterji go for it! :)

**Comment by fchatterji** [comment]
Hey, I tried to look at upgrading ruby, it creates a lot of errors in the test, that with my current knowledge of the codebase will be too long to fix. I just did the rails upgrade, will unassign myself from this issue.

**Comment by sylphiae** [comment]
I tried looking into upgrading Ruby and found that while the app ran locally fine, all of the tests failed. I added this gem to make the tests work "gem 'net-smtp', require: false" and then there were 45 failures. I think the stripe gem needs to be upgraded first because many of the failures were around the stripe tests.

**Comment by sylphiae** [comment]
Failures:

  1) StripeEventHelper ChargeFailed with no Stripe customer ID #call sends an email
     Failure/Error: let(:event) { StripeMock.mock_webhook_event("charge.failed") }
     
     NoMethodError:
       undefined method `exists?' for File:Class
     # /home/jenny/.rvm/gems/ruby-3.2.2/gems/stripe-ruby-mock-2.5.8/lib/stripe_mock/api/webhooks.rb:7:in `mock_webhook_payload'
     # /home/jenny/.rvm/gems/ruby-3.2.2/gems/stripe-ruby-mock-2.5.8/lib/stripe_mock/api/webhooks.rb:34:in `mock_webhook_event'
     # ./spec/helpers/stripe_event_helper_spec.rb:27:in `block (3 levels) in <top (required)>'
     # ./spec/helpers/stripe_event_helper_spec.rb:49:in `block (4 levels) in <top (required)>'

**Comment by ItsElaineTime** [comment]
Related? #489
